services:
  amd64:
    #build: environment/dockerfiles/amd64/notes
    image: ghcr.io/kanaderu/docker/amd64/notes:latest
    privileged: true
    network_mode: host
    working_dir: /app
    user: root
    volumes:
      - ./:/app

  build:
    #build: environment/dockerfiles/amd64/notes
    image: ghcr.io/kanaderu/docker/amd64/notes:latest
    privileged: true
    network_mode: host
    working_dir: /app/docs
    command: make html
    user: root
    volumes:
      - ./:/app
