services:
  amd64:
    #build: dockerfiles/amd64/notes
    image: ghcr.io/kanaderu/docker/amd64/notes:latest
    privileged: true
    network_mode: host
    working_dir: /app
    user: root
    volumes:
      - ./:/app
